<?xml version="1.0"?>
<robot name="tooro" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="link_width" value="0.01" />
  <xacro:property name="link_height" value="0.3" />
  <xacro:property name="camera_link" value="0.005" />
  <xacro:property name="axel_offset" value="0.005" />

  <xacro:include filename="$(find tooro_description)/urdf/common.xacro" /> 
  <xacro:include filename="$(find tooro_description)/urdf/materials.xacro" />

  <link name="world"/>

  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="base_link"/>
  </joint>

  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${link_height/2}" rpy="0 0 0"/>
      <xacro:box_geometry width="${link_width}" depth="${link_width}" height="${link_height}" />
      <xacro:brown_material />
    </visual>

    <xacro:box_collision z_origin="${link_height/2}" width="${link_width}" depth="${link_width}" height="${link_height}" />
    <xacro:box_inertia z_origin="${link_height/2}" mass="0.1" width="${link_width}" depth="${link_width}" height="${link_height}" />
  </link>

  <joint name="joint1" type="continuous">
    <parent link="base_link"/>
    <child link="link2"/>
    <origin xyz="0 ${link_width} ${link_height - axel_offset}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <link name="link2">
    <visual>
      <origin xyz="0 0 ${link_height/2 - axel_offset}" rpy="0 0 0"/>
      <xacro:box_geometry width="${link_width}" depth="${link_width}" height="${link_height}" />
      <xacro:black_material />
    </visual>

    <xacro:box_collision z_origin="${link_height/2 - axel_offset}" width="${link_width}" depth="${link_width}" height="${link_height}" />
    <xacro:box_inertia z_origin="${link_height/2- axel_offset}" mass="0.1" width="${link_width}" depth="${link_width}" height="${link_height}" />
  </link>

  <joint name="joint2" type="continuous">
    <parent link="link2"/>
    <child link="link3"/>
    <origin xyz="0 ${link_width} ${link_height - axel_offset*2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <link name="link3">
    <visual>
      <origin xyz="0 0 ${link_height/2 - axel_offset}" rpy="0 0 0"/>
      <xacro:box_geometry width="${link_width}" depth="${link_width}" height="${link_height}" />
      <xacro:brown_material />
    </visual>

    <xacro:box_collision z_origin="${link_height/2 - axel_offset}" width="${link_width}" depth="${link_width}" height="${link_height}" />
    <xacro:box_inertia z_origin="${link_height/2- axel_offset}" mass="0.1" width="${link_width}" depth="${link_width}" height="${link_height}" />
  </link>

  <joint name="camera_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="${camera_link} 0 ${link_height - axel_offset*2}" rpy="0 0 0"/>
    <parent link="link3"/>
    <child link="camera_link"/>
  </joint>

  <link name="camera_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <xacro:box_geometry width="${camera_link}" depth="${camera_link}" height="${camera_link}" />
      <xacro:red_material />
    </visual>

    <xacro:box_collision z_origin="0" width="${camera_link}" depth="${camera_link}" height="${camera_link}" />
    <xacro:box_inertia z_origin="0" mass="0.01" width="${camera_link}" depth="${camera_link}" height="${camera_link}"/>
  </link>

</robot>
