<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robone">

  <!-- Main file -->
  <xacro:include filename="$(find robone_description)/urdf/main.xacro"/>

  <gazebo>
    <plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
      <robotNamespace>/robone</robotNamespace>
    </plugin>
  </gazebo>

  <gazebo>
    <plugin name="joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so">
      <robotNamespace>/robone</robotNamespace>
      <jointName>wheel_holder_to_left_wheel, wheel_holder_to_right_wheel</jointName>
      <updateRate>100.0</updateRate>
      <alwaysOn>true</alwaysOn>
    </plugin>
  </gazebo>

  <gazebo>
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <alwaysOn>true</alwaysOn>
      <updateRate>50</updateRate>
<!-- Hack in order to make turns correct. Need to investigate why left and right are different for diff drive controller and model -->    
      <leftJoint>wheel_holder_to_right_wheel</leftJoint>
      <rightJoint>wheel_holder_to_left_wheel</rightJoint>
      <wheelSeparation>${base_radius}</wheelSeparation>
      <wheelDiameter>${wheel_radius * 2}</wheelDiameter>
      <publishWheelJointState>false</publishWheelJointState>
      <publishWheelTF>false</publishWheelTF>
<!-- Excluding due to error in validation of type -->
<!--      <publishTf>true</publishTf> -->
      <torque>20</torque>
      <commandTopic>cmd_vel</commandTopic>
      <odometryTopic>odom</odometryTopic>
      <odometryFrame>odom</odometryFrame>
      <odometrySource>world</odometrySource>
      <robotBaseFrame>base_link</robotBaseFrame>
      <rosDebugLevel>na</rosDebugLevel>
      <wheelAcceleration>0</wheelAcceleration>
      <wheelTorque>5</wheelTorque>
    </plugin>
  </gazebo>

  <gazebo reference="base_link">
    <material>Gazebo/White</material>
     <turnGravityOff>false</turnGravityOff>
  </gazebo>

  <!-- hokuyo -->
  <gazebo reference="hokuyo_link">
    <sensor type="ray" name="head_hokuyo_sensor">
      <pose>0 0 0 0 0 0</pose>
      <visualize>false</visualize>
      <update_rate>40</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>720</samples>
            <resolution>1</resolution>
            <min_angle>${-pi}</min_angle>
            <max_angle>${pi}</max_angle>
          </horizontal>
        </scan>
        <range>
          <min>${base_radius+0.1}</min>
          <max>30.0</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <!-- Noise parameters based on published spec for Hokuyo laser
               achieving "+-30mm" accuracy at range < 10m.  A mean of 0.0m and
               stddev of 0.01m will put 99.7% of samples within 0.03m of the true
               reading. -->
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_laser.so">
        <topicName>/robone/laser/scan</topicName>
        <frameName>hokuyo_link</frameName>
      </plugin>
    </sensor>
  </gazebo>

  <gazebo reference="left_wheel">
     <mu1 value="10.0" />
     <mu2 value="1.0" />
     <fdir1 value="1 0 0"/>
     <kp value="1000000.0"/>
     <kd value="100.0"/>
     <material>Gazebo/Black</material>
     <turnGravityOff>false</turnGravityOff>
  </gazebo>

  <gazebo reference="right_wheel">
     <mu1 value="10.0" />
     <mu2 value="1.0" />
     <fdir1 value="1 0 0"/>
     <kp value="1000000.0"/>
     <kd value="100.0"/>
     <material>Gazebo/Black</material>
     <turnGravityOff>false</turnGravityOff>
  </gazebo>

  <gazebo reference="forward_wheel">
     <mu1 value="10.0" />
     <mu2 value="1.0" />
     <fdir1 value="1 0 0"/>
     <kp value="1000000.0"/>
     <kd value="100.0"/>
     <material>Gazebo/Black</material>
     <turnGravityOff>false</turnGravityOff>
  </gazebo>

  <gazebo reference="hokuyo_link">
    <material>Gazebo/Red</material>
  </gazebo>

  <gazebo reference="left_wheel_holder">
    <material>Gazebo/Green</material>
  </gazebo>

  <gazebo reference="right_wheel_holder">
    <material>Gazebo/Green</material>
  </gazebo>

  <gazebo reference="forward_wheel_holder">
    <material>Gazebo/Green</material>
  </gazebo>


</robot>
