robone:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  left_wheel_position_controller:
    type: velocity_controllers/JointVelocityController
    #type: effort_controllers/JointPositionController
    #joint: wheel_holder_to_left_wheel
    joint: left_motor
    #pid: {p: 0, i: 0.01, d: 0.01, i_clamp: 100}
    #pid: {p: 10.0, i: 0.01, d: 1.0} 
    #pid: {p: 5.0, i: 20.0, d: 0.0, i_clamp: 100}
  right_wheel_position_controller:
    type: velocity_controllers/JointVelocityController
    #type: effort_controllers/JointPositionController
    joint: wheel_holder_to_right_wheel
    #pid: {p: 10, i: 1, d: 1, i_clamp: 100}
    #pid: {p: 10.0, i: 0.01, d: 1.0}
    #pid: {p: 5.0, i: 20.0, d: 0.0, i_clamp: 100}
