map_type: costmap
transform_tolerance: 0.2
obstacle_range: 2.5
raytrace_range: 3.0
#footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
footprint: [[0.15, 0], [0, 0.15], [-0.15,0], [0, -0.15]]
robot_radius: 0.15
inflation_radius: 0.55

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo_link, 
                    data_type: LaserScan, 
                    topic: /robone/laser/scan, 
                    marking: true, 
                    clearing: true}

